tranches_IR:
  - [0, 11295, 0]  # min (€), max (€), taux (%)
  - [11296, 29787, 11]  # min (€), max (€), taux (%)
  - [29788, 82342, 30]  # min (€), max (€), taux (%)
  - [82343, 177106, 41]  # min (€), max (€), taux (%)
  - [177107, 99999999999999999999999, 45]  # min (€), max (€), taux (%)

TVA:
  taux_normal: 20  # (%)
  taux_reduit: 5.5  # (%)
  taux_intermediaire: 10  # (%)

SASU:
  salaires:
    charges_sociales:
      taux_cotisation: 70  # (%) pour 30000€ de salaire net, l'entreprise payera 30000 + 30000 * 0.85 = 55500€
      taux_inverse_approximatif: 46  # (%) si l'entreprise verse 55500€, le salarié touchera 55500 - 55500 * 0.46 = 29970€
  dividendes:
    prelevements_sociaux: 
      - CSG_deductible: 6.8 # (%) Contribution Sociale Généralisée
      - CSG_non_deductible: 2.4 # (%) Contribution Sociale Généralisée
      - CRDS: 0.5 # (%) Contribution pour le Remboursement de la Dette Sociale
      - solidarite: 7.5 # (%) Contribution pour la Solidarité
    prelevements_sociaux_total: 17.2 # (%) Taux global des prélèvements sociaux
    TMI: 12.8  # (%) Taux Marginal d'Imposition (non-cumulatif avec IR)
    abattement: 40  # (%)
  tranches_IS:
      - [0, 42500, 15]  # min (€), max (€), taux (%)
      - [42500, inf, 25]  # min (€), max (€), taux (%)
EURL:
  salaires:
    charges_sociales:
      taux_cotisation: 42  # (%) pour 30000€ de salaire net, l'entreprise payera 30000 + 30000 * 0.45 = 43500€
      taux_inverse_approximatif: 31  # (%) si l'entreprise verse 43500€, le salarié touchera 43500 - 43500 * 0.31 = 30015€

