tranches_IR:
  - [0, 11295, 0]  # min (€), max (€), taux (%)
  - [11296, 29787, 11]  # min (€), max (€), taux (%)
  - [29788, 82342, 30]  # min (€), max (€), taux (%)
  - [82343, 177106, 41]  # min (€), max (€), taux (%)
  - [177107, 99999999999999999999999, 45]  # min (€), max (€), taux (%)

TVA:
  taux_normal: 20  # (%)
  taux_reduit: 5.5  # (%)
  taux_intermediaire: 10  # (%)

dividendes:
    prelevements_sociaux: 17.2  # (%) 
    CSG: 6.8  # (%) Contribution Sociale Généralisée (/!\ déjà compté dans les <prelevements_sociaux>)
    TMI: 12.8  # (%) Taux Marginal d'Imposition (non-cumulatif avec IR)
    abattement: 40  # (%)

societe:
  EURL:
    charges_sociales:
      taux: 45  # (%) pour 30000€ de salaire net, l'entreprise payera 30000 + 30000 * 0.45 = 43500€
      taux_inverse_approximatif: 31  # (%) si l'entreprise verse 43500€, le salarié touchera 43500 - 43500 * 0.31 = 30015€
  SASU:
    charges_sociales:
      taux: 85  # (%) pour 30000€ de salaire net, l'entreprise payera 30000 + 30000 * 0.85 = 55500€
      taux_inverse_approximatif: 46  # (%) si l'entreprise verse 55500€, le salarié touchera 55500 - 55500 * 0.46 = 29970€
    tranches_IS:
      - [0, 38120, 15]  # min (€), max (€), taux (%)
      - [38120, inf, 25]  # min (€), max (€), taux (%)